### ISSUE TITLE
[API Gateway] 각 서비스 연결 테스트

### ISSUE THREAD

**Issue by oereo** [MSAFriends/ecommerce#25]
## Description
- `member-service`,  `order-service`, `product-service`에 대해서 각 Internal API를 통해 호출이 잘 되는지와 전체적인 기능이 잘 작동하는지 확인

## Todo
- [x] :  order-service에서 주문하기 API의 작동여부 파악
  - [x] : 쿠폰 조회 API 연결 확인
  - [x] : 쿠폰 사용 API 연결 확인
  - [x] : 상품 조회 API 연결 확인 
- [x] : product-service에서 마일리지 적립 event가 발생했을 시 member-service이 마일리지 업데이트 API 작동 여부 파악
  - [x] : 회원이 가지고 있는 마일리지와 마일리지 event 이력의 마일리지 총합이 일치하는지 여부 확인
