### ISSUE TITLE
[product-service] Category 도메인 관련 API 개발

### ISSUE THREAD

**Issue by GangminRYOU** [MSAFriends/ecommerce#29]
## Description
Category 도메인 CRUD API 개발

## Todo
- [x]: 관리자는 카테고리를 등록할 수 있다.
- [x]: 다른 Micro-service와 사용자는 전체 카테고리를 조회할 수 있다.
- [x]: 사용자는 카테고리별로 상품을 조회 할 수 있다.
- [x]: 관리자는 카테고리를 삭제할 수 있다.

### 고려할 점
- 상위 카테고리 삭제시, 하위 카테고리에 대한 수정
 - 상위 카테고리 삭제시, 하위 카테고리 전부 삭제
 - 상위 카테고리 삭제시, 하위 카테고리 상위 level로 수정
