### ISSUE TITLE
[order-service] 주문하기 관련 API 개발

### ISSUE THREAD

**Issue by destitutor** [MSAFriends/ecommerce#33]
## Description
멤버가 상품을 장바구니에 담고 주문할 수 있는 API 개발

## Todo
- [x] 멤버 서비스와 상품 서비스 간에 정상적으로 통신이 이루어지는지 확인해야 함
- [x] 주문이 정상적으로 이루어졌을 때, 쿠폰을 사용 처리하고 상품의 재고가 정상적으로 감소되었는지 확인해야 함
- [ ] ~~`Eventuate Tram`을 통해서 사가 패턴을 구현하여 주문 실패 시 사용되는 보상 트랜잭션을 구현해야 함~~

## ETC
가급적이면 트릭이나 기교를 통해 트랜잭션을 회피하는 게 좋지만, 현재로서는 마땅한 방법이 없다고 판단하여 사가 패턴을 통해서 분산 트랜잭션을 구현하기로 했습니다.
이미 만들어진 기능을 다시 개발하는 것은 의미가 없다고 생각했으므로 `Eventuate Tram`과 `Axon Framework` 중 하나를 고려하였으며, 단순히 사가 패턴을 보다 쉽게 도입하려는 목적으로 의존성을 추가하기 위함이라 EDA나 DDD를 위해 만들어진 Axon Framework를 고려 대상에서 배제하기로 결정했습니다.

> 전통적인 JDBC/JPA 기반의 영속성 모델을 사용하는 Java/Spring 기반의 마이크로서비스를 위한 것이다. 이벤트 소싱(event sourcing)과는 다르게, Java/Spring Boot 애플리케이션에 사가 패턴(saga pattern)이나 CQRS를 도입하기 위해서 전반적인 코드나 아키텍처를 크게 변경할 필요 없이 Eventuate Tram을 도입할 수 있다.

## References
- https://eventuate.io/abouteventuatetram.html
