### ISSUE TITLE
[Redis] 캐싱 전략 수립

### ISSUE THREAD

**Issue by oereo** [MSAFriends/ecommerce#43]
## Description
JMeter로 테스트를 진행했을 때 평균 응답 속도가 느린 문제 개선

## Todo
- [ ] :  캐싱전략 수립
  - [x] : Data persistence strategy
  - [x] : Cache strategy
  - [x] : Data persistence와 cache 전략들을 조합하여 구현체로 개발
  - [ ] : 각 조합에 대해서 각 서비스에 맞는 캐싱전략 수립
